name = "cloudflare-demo-ui"
compatibility_date = "2024-01-15"
workers_dev = true
account_id = "441173fa8f21b10fb5747318e0da4e75"

# Pages configuration
pages_build_output_dir = "."

[site]
bucket = "."

# Environment variables
[vars]
API_BASE_URL = "https://cloudflare-demo-project.youqi-nie.workers.dev"
